services:
  # Combined Backend and Frontend Service
  - type: web
    name: lounge-app # Simplified name for the combined service
    env: node
    region: oregon
    branch: main
    rootDir: partner-backend # Root is still where package.json and server.ts are
    plan: free
    buildFilter: # Optional: rebuild only if backend or frontend files change
      paths:
      - partner-backend/server.ts
      - partner-backend/initial-lounge-data.json
      - partner-backend/partner-frontend/**
    # Build command now includes steps for both frontend and backend:
    # 1. Install backend dependencies
    # 2. Change to partner-frontend, install its dependencies, and build it
    # 3. Change back (implicitly) and build the backend (tsc)
    buildCommand: npm install && (cd partner-frontend && npm install && npm run build) && npm run build
    startCommand: npm start    # Runs node dist/server.js
    healthCheckPath: /api/offers # Health check for the API
    envVars:
      - key: NODE_VERSION
        value: 20
    # Note: Static files are served by Express from 'partner-frontend'
    # The express.static path is relative to dist/server.js: path.join(__dirname, '../partner-frontend')
    # No separate static site configuration is needed here.
    # Routes for SPA behavior (serving index.html) are handled in server.ts
