services:
  # Backend Service: Node.js Express App
  - type: web
    name: lounge-partner-backend
    env: node
    region: oregon
    branch: main
    rootDir: partner-backend
    plan: free
    buildFilter:
      paths:
      - partner-backend/**
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/offers
    envVars:
      - key: NODE_VERSION
        value: 18

  # Frontend Service: Static Site (deployed as web service with static files)
  - type: web
    name: lounge-partner-frontend
    env: static
    region: oregon
    branch: main
    rootDir: partner-backend/partner-frontend
    plan: free
    buildFilter:
      paths:
      - partner-backend/partner-frontend/**
    # publishDir: . # Not used with env: static, staticPublishPath is used instead
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
